server:
  port: 800

#spring
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
  rabbitmq:
    #    DSK
    addresses: 10.160.144.8:5672
    username: admin
    password: admin123456
    template:
      receive-timeout: 40000
      reply-timeout: 40000
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000
        default-requeue-rejected: false
  #    listener:
  #      retry:
  #        max-attempts: 3
  #        enabled: true
  session:
    store-type: none
  devtools:
    restart:
      enabled: true        #这里是为了热部署的，与mybatis是无关的
  cache:
    type: redis
  mail:                    #邮件发送
    host: msout.sanken-ele.co.jp
    username: lihuan@ms5.sanken-ele.co.jp
    sender: CIM-INFO<lihuan@ms5.sanken-ele.co.jp>
    password: hl1018%a
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
  redis:   #redis 配置
    host: localhost
    port: 6378
    password: Ivo!@#
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000
  messages: #国际化
    basename: i18n/messages,i18n/ValidationMessages
  mvc: # 捕获404
    throw-exception-if-no-handler-found: true
  thymeleaf: #关闭默认模板引擎
    cache: false
    enabled: false
  aop:  #使用CGLIB来实现AOP的时候
    proxy-target-class: true

  #DATABASE CONFIG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://10.160.144.8:3316/dskcim?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    connection-properties: druid.stat.merggSql=ture;druid.stat.slowSqlMillis=5000

##mybatis
#mybatis:
#  mapper-locations: classpath*:/mapper/**/*.xml   #把xml文件放在com.XX.mapper.*中可能会出现找到的问题，这里把他放在resource下的mapper中
#  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.lmrj.cim.modules.*.entity  #这里是实体类的位置
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:  com.lmrj.**.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  configuration-properties:
    dbType: oracle #设置全局属性用于控制数据库的类型

#logging
logging:
  level:
    #    root: debug
    com.lmrj.eap.modules: DEBUG

#shiro
shiro:
  filter-chain-definitions: /swagger/api-docs=anon;/v2/api-docs=anon;/swagger-resources/**=anon;/swagger-ui.html=anon;/webjars/**=anon;/monitor/druid/**=anon;/jcaptcha*=anon;/oss/upload/**=anon;/sso/oauth2/**=anon;/**=authc;/services/*=anon;

#定时任务配置
quartz:
  open-cluster: false # 是否开启集群
  config-location: /quartz/quartz.properties # 集群配置文件路径
  data-source: qzDS # 集群数据库，使用当前数据库可以设置为空或者default

#swagger配置
swagger:
  enabled: true
  title: lmrj管理系统_接口文档
  description: 描述：具体包括XXX,XXX模块...
  version: 1.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl:
  contact.name: 张飞
  contact.url: http://www.lmrj.com
  contact.email: zhangwj@lmrj.com
  base-package: com.lmrj
  base-path: /**
  exclude-path: /error, /ops/**
  global-operation-parameters[0]:
    name: access_token
    description: 用户Access_token
    modelRef: string
    parameterType: header
    required: true
  ui-config:
    json-editor: false
    show-request-headers: true
    request-timeout: 5000
    submit-methods: get,delete

#文件上传配置
upload:
  base:
    dir: /upload
    imgurl: http://10.160.144.8:83/img
    imgdir: E:/CIM/share/img/
  allowed:
    #允许的文件扩展名
    extension: mp4,bmp, gif, jpg, jpeg, png,doc, docx, xls, xlsx, ppt, pptx,html,htm,txt,rar, zip, gz, bz2,pdf
  max:
    size: 52428800 #最大文件大小 50M

aps:
  dir: D:\1项目\大连三垦\2需求分设\APS\
